matrix:
  include:
  - language: rust
      script:
        - rustc code/_init_rust.rs
        - ./_init_rust
  - language: verilog
      install:
        - sudo apt-get install -y iverilog
      script:
        - iverilog code/__initVerilog__.v
